title: Mitch's Blog
description: My Personal Website
author: Mitch Beebe
github: https://github.com/mitchbeebe
about: I'm a Data Scientist and passionate R and Python programmer. This is my personal site where I may write the occasional blog post about data science, sports, or something I find funny.
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://linkedin.com/mitchbeebe"
    - icon: fa-github
      link: "https://github.com/mitchbeebe"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://mitchbeebe.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
