title: Mitch's Blog
description: My Personal Website
author: Mitch Beebe
github: https://github.com/mitchbeebe
about: Data Scientist at JPMorgan Chase
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/mitchbeebe"
    - icon: fa-linkedin
      link: "https://linkedin.com/mitchbeebe"
    - icon: fa-twitter
      link: "https://twitter.com/mitchbeebe"

urls:
    - text: Blog
      url: /blog/
    - text: Projects
      url: /projects/

url: "https://mitchbeebe.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blog/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
